In [62]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [63]:
iris = load_iris()

iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [64]:
iris_data = iris.data

iris_label = iris.target

In [65]:
df_iris = pd.DataFrame(iris_data, columns = iris.feature_names)

df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [66]:
X = df_iris.iloc[:, :-1]
y = df_iris.iloc[:, [-1]]

In [67]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)
0                  5.1               3.5                1.4
1                  4.9               3.0                1.4
2                  4.7               3.2                1.3
3                  4.6               3.1                1.5
4                  5.0               3.6                1.4
..                 ...               ...                ...
145                6.7               3.0                5.2
146                6.3               2.5                5.0
147                6.5               3.0                5.2
148                6.2               3.4                5.4
149                5.9               3.0                5.1

[150 rows x 3 columns]

In [68]:
y

petal width (cm)
0                 0.2
1                 0.2
2                 0.2
3                 0.2
4                 0.2
..                ...
145               2.3
146               1.9
147               2.0
148               2.3
149               1.8

[150 rows x 1 columns]

In [77]:
X = iris.data
y = iris.target

In [78]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

In [79]:
print("X_train.shape:", X_train.shape)

print("y_train.shape:", y_train.shape)

print("X_test.shape:", X_test.shape)

print("y_test.shape:", y_test.shape)

X_train.shape: (120, 4)
y_train.shape: (120, 3)
X_test.shape: (30, 4)
y_test.shape: (30, 3)


In [121]:
#Defining the model 

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD,Adam
from keras.layers import Input, Dense
from keras.models import Model

# 이는 텐서를 반환합니다
inputs = Input(shape=(3,))
x = Dense(20, activation='relu')(inputs)
x2 = Dense(15, activation='relu')(x)
x3 = Dense(10, activation='relu')(x2)
output=Dense(1,activation='softmax')(x3)

model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_35 (Dense)            (None, 64)                320       
                                                                 
 dense_36 (Dense)            (None, 64)                4160      
                                                                 
 dense_37 (Dense)            (None, 1)                 65        
                                                                 
Total params: 4,545
Trainable params: 4,545
Non-trainable params: 0
_________________________________________________________________


In [122]:
#fitting the model and predicting 

# fit network
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
4/4 [==============================] - 0s 64ms/step - loss: 0.2226 - mae: 0.4446 - val_loss: 0.2231 - val_mae: 0.4527
Epoch 2/100
4/4 [==============================] - 0s 34ms/step - loss: 0.2227 - mae: 0.4453 - val_loss: 0.2225 - val_mae: 0.4484
Epoch 3/100
4/4 [==============================] - 0s 36ms/step - loss: 0.2223 - mae: 0.4448 - val_loss: 0.2224 - val_mae: 0.4467
Epoch 4/100
4/4 [==============================] - 0s 34ms/step - loss: 0.2223 - mae: 0.4441 - val_loss: 0.2227 - val_mae: 0.4505
Epoch 5/100
4/4 [==============================] - 0s 34ms/step - loss: 0.2227 - mae: 0.4446 - val_loss: 0.2226 - val_mae: 0.4499
Epoch 6/100
4/4 [==============================] - 0s 35ms/step - loss: 0.2224 - mae: 0.4449 - val_loss: 0.2226 - val_mae: 0.4482
Epoch 7/100
4/4 [==============================] - 0s 36ms/step - loss: 0.2224 - mae: 0.4444 - val_loss: 0.2227 - val_mae: 0.4505
Epoch 8/100
4/4 [==============================] - 0s 39ms/step - loss: 0.2226 - mae: 0.44

4/4 [==============================] - 0s 37ms/step - loss: 0.2226 - mae: 0.4438 - val_loss: 0.2224 - val_mae: 0.4428
Epoch 64/100
4/4 [==============================] - 0s 35ms/step - loss: 0.2223 - mae: 0.4441 - val_loss: 0.2223 - val_mae: 0.4427
Epoch 65/100
4/4 [==============================] - 0s 34ms/step - loss: 0.2225 - mae: 0.4443 - val_loss: 0.2227 - val_mae: 0.4407
Epoch 66/100
4/4 [==============================] - 0s 34ms/step - loss: 0.2224 - mae: 0.4439 - val_loss: 0.2224 - val_mae: 0.4425
Epoch 67/100
4/4 [==============================] - 0s 32ms/step - loss: 0.2224 - mae: 0.4442 - val_loss: 0.2225 - val_mae: 0.4417
Epoch 68/100
4/4 [==============================] - 0s 31ms/step - loss: 0.2225 - mae: 0.4440 - val_loss: 0.2227 - val_mae: 0.4398
Epoch 69/100
4/4 [==============================] - 0s 33ms/step - loss: 0.2225 - mae: 0.4437 - val_loss: 0.2224 - val_mae: 0.4434
Epoch 70/100
4/4 [==============================] - 0s 35ms/step - loss: 0.2223 - mae: 0.4443 - 

In [123]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.37      1.00      0.54        11
           1       0.00      0.00      0.00        13
           2       0.00      0.00      0.00         6

    accuracy                           0.37        30
   macro avg       0.12      0.33      0.18        30
weighted avg       0.13      0.37      0.20        30

[[11  0  0]
 [13  0  0]
 [ 6  0  0]]


C:\Users\82109\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\82109\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\82109\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
